### ISSUE TITLE
K úkolu č. 2

### ISSUE THREAD

**Issue by ifischerova** [Klatnik/PROJEKT-Vizitka#1]
Ahoj Katko, skvělá práce 👍  

Posílám jen pár tipů a prosím o doplnění pseudotříd :-) 

-  U `h1` myslím nemusíš explicitně dávat `margin-bottom: 30px;` protože defaultní margin `h1` je zhruba stejný. Explicitně to tam napsat samozřejmě ničemu nevadí, jen máš možnost ušetřit řádku kódu. 
-  Nech VS Code vždy zformátovat kód v index.html a style.css, sám Ti to pěkně srovná a dá kódu "štábní kulturu" :-)
-  Většinu vlastností, co máš v selektorech `.twitter` a `.facebook` můžeš dát rovnou do `<a>`, protože jsou shodné a v `.twitter` a 
`.facebook` nechat jen to, čím se liší. 
-  [x] `.twitter` a `.facebook` by měly mít ještě pseudotřídy `:hover` a `:focus`. Můžeš to zapsat jako vícenásobný selektor k `:active`, ale pozor na [pořadí pseudotříd](https://developer.mozilla.org/en-US/docs/Web/CSS/:active).

**Comment by Klatnik** [comment]
Pseudotřídy doplněny + upraven zbytek

**Comment by ifischerova** [comment]
Ahoj, super 👍
